full_rebuild: true
name: Photon Book Creator
author: Cédric Soulas
url: https://pymloaccounting.github.io/pymloaccounting
repository: https://github.com/pymloaccounting/pymloaccounting
branch: gh-pages
version: 1.3
encoding: utf-8
themes:
    # General themes available: minimal, freelancer
    general: minimal
    # Code block themes available: monokai, github, vs
    code: monokai
defaults:
  -
    values:
      layout: "index"
exclude: [
.git,
.gitignore,
README.md,
LICENSE
]
